services:
  codey-bot:
    image: codey:latest
    container_name: codey-bot
    restart: always
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
      - ./db:/usr/app/db
      - ./docs:/usr/app/docs
