services:
  codey-bot:
    image: uwcsclub/codey-bot:latest-prod
    container_name: codey-production
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/app/logs
      - ./db:/usr/app/db
      