services:
  codey-bot:
    image: uwcsclub/codey-bot:latest-staging
    container_name: codey-staging
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=staging
    volumes:
      - ./logs:/usr/app/logs
      - ./db:/usr/app/db
